version: '3.8'

services:
  auth-tester:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-tester
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge 